# Generated by Django 5.0.4 on 2024-04-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('prices', models.JSONField(blank=True, null=True)),
                ('image', models.CharField(max_length=128)),
                ('product_link', models.CharField(max_length=256)),
                ('product_code', models.IntegerField(db_index=True)),
                ('description', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'alcohol',
                'verbose_name_plural': 'alcohols',
            },
        ),
    ]
