name: alcohol workflow

on:
  workflow_dispatch:
    inputs:
      alco:
        description: 'choice alcohol or lint code'  #
        default: 'lint'
        required: true
        type: choice
        options:
          - find
          - lint
  schedule:
    - cron: '0 20 * * 6'
#  push:
#    branches:
#      - "main"

jobs:
  scrap_alcohol:
    runs-on:
      ubuntu-latest
    if: inputs.alco == 'find' || github.event.schedule == '0 20 * * 6'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: install dependencies
        run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
      - name: install google-chrome
        run: sudo apt-get install google-chrome-stable

      - name: start scrapping
        run: python run.py --browser undetected
      - name: commit changes
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.Qauto }}
          add: 'data'
          author_name: oleh lykhorovych
          message: 'add new alcohol'

  lint_code:
    runs-on: ubuntu-latest
    if: ${{ inputs.alco == 'lint' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: install dependencies
        run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
      - name: lint with Ruff
        run: |
          pip install ruff
          ruff --output-format=github .
        continue-on-error: true
          

