name: Find products with economy
on:
   schedule:
     - cron: '0 12 * * 3'  # if github.event.schedule != '0 18 * * 6'
jobs:
  search_products_with_economy:
    runs-on:
      ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: install google-chrome
        run: sudo apt-get install google-chrome-stable
      - name: start scrapping
        run: |
             python manage.py runscript run_script --script-args undetected headless
      - name: commit changes
        uses: EndBug/add-and-commit@v9
        with:
            github_token: ${{ secrets.Qauto }}
            author_name: oleh lykhorovych
            message: 'add products with economy $(date)'
