name: "job scheduler"
on:
   schedule:
     - cron: '30 18 * * 6'
jobs:
  search_alcohol:
    runs-on:
      ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: install google-chrome
        run: sudo apt-get install google-chrome-stable
      - name: start scrapping
        run: |
             python run.py --browser undetected
      - name: commit changes
        uses: EndBug/add-and-commit@v9
        with:
            github_token: ${{ secrets.Qauto }}
            add: 'data'
            author_name: oleh lykhorovych
            message: 'add new alcohol'
