# Generated by Django 5.0.6 on 2024-06-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField()),
                ('discount', models.SmallIntegerField()),
                ('name', models.CharField(blank=True, help_text='product description', max_length=128, null=True)),
                ('image', models.URLField(blank=True, help_text='link to image', null=True)),
                ('link', models.URLField(blank=True, help_text='product link', null=True)),
                ('price_top', models.FloatField(help_text='price without discount')),
                ('price_bottom', models.FloatField(help_text='price with discount')),
                ('price_statistic', models.JSONField(blank=True, null=True)),
                ('in_economy', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_ends', models.BooleanField(default=False)),
            ],
        ),
    ]
